### PR TITLE
Created box to publish a new post

### PR DESCRIPTION
**Pull request by tissyane**
Created component box to publish a new post - desktop and responsive (using Timeline Page provisory)

### CODE REVIEW

**Review by guilhermeicarofr — APPROVED** [review]
Looks ok, I will refactor the TimelineProvisória component after merge for ir to be the definitive version

**Review by Francksuel — APPROVED** [review]
Refactor button and input components

**Comment by tissyane** [comment]
> Looks ok, I will refactor the TimelineProvisória component after merge for ir to be the definitive version

Perfect! Thanks!

**Comment by tissyane** [comment]
> Refactor button and input components

Yes, I'll do it!

**Pull request merged**
